// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.Api.Infrastructure.Data;

#nullable disable

namespace OrderManagement.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(OrderManagementDbContext))]
    partial class OrderManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagement.Api.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d94d8bdf-ffcf-4f09-865a-fc3444510aa7"),
                            CreatedAt = new DateTime(2025, 5, 31, 20, 27, 8, 118, DateTimeKind.Utc).AddTicks(2401),
                            CustomerId = new Guid("c6326406-e65f-44d1-82e3-880c09c823ec"),
                            Status = 0,
                            TotalAmount = 5000m
                        },
                        new
                        {
                            Id = new Guid("89b166d4-ac78-4c21-97c2-8944eaccdb43"),
                            CreatedAt = new DateTime(2025, 5, 31, 20, 27, 8, 118, DateTimeKind.Utc).AddTicks(2496),
                            CustomerId = new Guid("523bca92-5f31-438c-a877-f2909837c2b8"),
                            Status = 2,
                            TotalAmount = 10000m
                        });
                });

            modelBuilder.Entity("OrderManagement.Api.Domain.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerSegment")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerSegment");

                    b.HasIndex("ValidFrom");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0aec6cd5-ace9-490b-ba10-33fe85cc5aae"),
                            CustomerSegment = "New",
                            Name = "Vuka",
                            Type = "Percentage",
                            ValidFrom = new DateTime(2025, 5, 31, 20, 27, 8, 117, DateTimeKind.Utc).AddTicks(9307),
                            Value = 10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
